[tool]
id = "copybook"

[[dependency]]
path = "build/libs/copybook-cli-@project.version@.jar"

[[dependency]]
path = "build/libs/antlr4-runtime-@toml.antlrVersion@.jar"

[[dependency]]
path = "build/libs/copybook-commons-@toml.copybookParserVersion@.jar"
