[tool]
id = "copybook"

[[dependency]]
path = "build/libs/copybook-cli-0.1.2-SNAPSHOT.jar"

[[dependency]]
path = "build/libs/antlr4-runtime-4.13.1.jar"

[[dependency]]
path = "build/libs/copybook-commons-0.1.2-20231115-100000-cae814e.jar"
