[tool]
id = "copybook"

[[dependency]]
path = "build/libs/copybook-cli-0.1.1-SNAPSHOT.jar"

[[dependency]]
path = "build/libs/antlr4-runtime-4.13.1.jar"

[[dependency]]
path = "build/libs/copybook-commons-0.1.1.jar"
